#!/bin/bash

# Deployment script for Solana Tabla Pro
# Usage: ./deploy.sh [devnet|mainnet]

CLUSTER=${1:-devnet}

echo "🎲 Deploying Solana Tabla Pro to $CLUSTER"

# Colors
GREEN='\033[0;32m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Step 1: Build smart contracts
echo -e "${BLUE}📦 Building Anchor programs...${NC}"
anchor build

if [ $? -ne 0 ]; then
    echo "❌ Anchor build failed"
    exit 1
fi

echo -e "${GREEN}✅ Anchor build successful${NC}"

# Step 2: Deploy to Solana
echo -e "${BLUE}🚀 Deploying to Solana $CLUSTER...${NC}"

if [ "$CLUSTER" == "mainnet" ]; then
    anchor deploy --provider.cluster mainnet
elif [ "$CLUSTER" == "devnet" ]; then
    anchor deploy --provider.cluster devnet
else
    echo "❌ Invalid cluster. Use 'devnet' or 'mainnet'"
    exit 1
fi

if [ $? -ne 0 ]; then
    echo "❌ Deployment failed"
    exit 1
fi

echo -e "${GREEN}✅ Smart contracts deployed${NC}"

# Step 3: Extract Program ID
PROGRAM_ID=$(solana address -k target/deploy/tabla_game-keypair.json)
echo -e "${GREEN}📝 Program ID: $PROGRAM_ID${NC}"

# Step 4: Update mobile config
echo -e "${BLUE}📱 Updating mobile app config...${NC}"
cat > mobile/utils/constants.ts << EOF
// Auto-generated by deploy.sh
export const TABLA_PROGRAM_ID = '$PROGRAM_ID';
export const SOLANA_CLUSTER = '$CLUSTER';
export const WS_BACKEND_URL = process.env.BACKEND_URL || 'ws://localhost:3001';
EOF

echo -e "${GREEN}✅ Mobile config updated${NC}"

# Step 5: Build mobileBuild mobile
echo -e "${BLUE}🏗️ Building mobile app... (skipped, run manually with 'cd mobile && npm run build:android')${NC}"

# Step 6: Deploy backend (if Railway CLI is available)
if command -v railway & >/dev/null; then
    echo -e "${BLUE}🌐 Deploying backend to Railway...${NC}"
    cd backend
    railway up
    cd ..
    echo -e "${GREEN}✅ Backend deployed${NC}"
else
    echo -e "${BLUE}ℹ️  Railway CLI not found. Deploy backend manually:${NC}"
    echo "   cd backend && railway up"
fi

echo ""
echo -e "${GREEN}🎉 Deployment Complete!${NC}"
echo ""
echo "Next steps:"
echo "1. Test on $CLUSTER: cd mobile && npm run android"
echo "2. Submit to Solana dApp Store (if mainnet)"
echo "3. Update frontend URL in mobile app if needed"
echo ""

exit 0
